### ISSUE TITLE
Warnings for deprecated functions

### ISSUE THREAD

**Issue by flokX** [komoot/leaflet.photon#18]
If I use the current release ofthe plugin with the latest leaflet release, there are a few warnings:

_leaflet.js:5 Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at y ([...]/leaflet.js:5:2081)
    at Function.v.extend ([...]/leaflet.js:5:14792)
    at [...]/leaflet.photon.js:51:35_

_leaflet.js:5 Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at y ([...]/leaflet.js:5:2081)
    at Function.v.extend ([...]/leaflet.js:5:14792)
    at [...]/leaflet.photon.js:386:30_

_leaflet.js:5 Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at y ([...]/leaflet.js:5:2081)
    at Function.v.extend ([...]/leaflet.js:5:14792)
    at [...]/leaflet.photon.js:426:32_

The plugin works well, but maybe it doesnt; work well when these features are removed.

**Comment by jmelvin** [comment]
The deprecation warning does not show using the latest leaflet.photon.js.
